In [1]:
import numpy as np
import pandas as pd  
import random

In [2]:
# Create a list of 5 integer

my_list = [10,20,30,40,50]
print("List: ", my_list)

List:  [10, 20, 30, 40, 50]


In [3]:
# append
my_list.append(60)
print("append: ", my_list)

append:  [10, 20, 30, 40, 50, 60]


In [4]:
# Extend
my_list.extend ([70,80])
print("extend([70,80]):", my_list)

extend([70,80]): [10, 20, 30, 40, 50, 60, 70, 80]


In [5]:
# insert
my_list.insert(2,25)
print ("insert(2,5): ", my_list)

insert(2,5):  [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [6]:
# remove
my_list.remove(40)
print("remove(40): ", my_list)

remove(40):  [10, 20, 25, 30, 50, 60, 70, 80]


In [7]:
# Pop - remove last or by index
popped = my_list.pop()
print("popped element: ", popped)
print ("pop: ", my_list)

popped element:  80
pop:  [10, 20, 25, 30, 50, 60, 70]


In [8]:
# index 
idx = my_list.index(30)
print ("Index: ", idx)

Index:  3


In [9]:
# Count 
count = my_list.count(60)
print(count)

1


In [10]:
# Sort
my_list.sort()
print ("sort: ", my_list)

sort:  [10, 20, 25, 30, 50, 60, 70]


In [11]:
# reverse
my_list.reverse()
print(my_list)

[70, 60, 50, 30, 25, 20, 10]


In [12]:
# clear
my_list.clear()
print ("clear: ", my_list)

clear:  []


In [13]:
# Create tuple with 3 student names

students = ("Krishna", "Devender", "Danish")
print (students)

# Change second name 
try:
    students[1]= "Krishna"
except TypeError as e:
    print ("Error:", e)
    print ("Reason: Tuples are immutable once created, their elements can not be changed")

('Krishna', 'Devender', 'Danish')
Error: 'tuple' object does not support item assignment
Reason: Tuples are immutable once created, their elements can not be changed


In [14]:
#3. Create a set of integers with some duplicate values. Print the set and explain the output

num_set = {1,4,8,5,8,2,3}
print (num_set)
print("Explanation: Sets automatically remove duplicate values and store only unique elements.")

{1, 2, 3, 4, 5, 8}
Explanation: Sets automatically remove duplicate values and store only unique elements.


In [15]:
# Create dictionary
Person = {'name': 'Waquar', 'age': 25, 'city': 'Mumbai'}
print("Original:", Person)

# update age
Person['age'] = 28

# Add new key 'email'
Person['email'] = 'Waquar@example.com'

print("Final dictionary:", Person)

Original: {'name': 'Waquar', 'age': 25, 'city': 'Mumbai'}
Final dictionary: {'name': 'Waquar', 'age': 28, 'city': 'Mumbai', 'email': 'Waquar@example.com'}


In [16]:
# Voting eligibility

age = int(input("Enter age: "))
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter age:  18


Eligible to vote


In [17]:
# 6 Grade based on Marks

marks = int(input("Enter marks: "))
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'
print("Grade:", grade)

Enter marks:  50


Grade: C


In [18]:
# 7 check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

num = int(input("Enter a number: "))
if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number:  5


Positive number
It is odd


In [19]:
# Section B: Numpy
# 8 Create Array

# Scalar
scalar = np.array(5)
print("Scalar:", scalar, "| Shape:", scalar.shape)

# 1D array 1 to 5
arr1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1d)

# 2D array (2x3) from 10 to 60 step 10
arr2d = np.arange(10, 70, 10).reshape(2, 3)
print("2D array:\n", arr2d)

Scalar: 5 | Shape: ()
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [20]:
# 9 4x4 array

random_arr = np.random.randint(0, 101, size=(4, 4))
print("4x4 random array:\n", random_arr)

4x4 random array:
 [[17 98 68 77]
 [47 96 34 81]
 [46 85 91  6]
 [14 61 49 76]]


In [21]:
# 3x3 array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert to DataFrame with column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [22]:
# Section C: Exploring Pandas

# Create DataFrame with 10 rows
data = {
    'Name': ['Krish', 'Ram', 'Sita', 'David', 'Sumit', 
             'Aman', 'dev', 'Anish', 'Raghav', 'Waquar'],
    'Age': [25, 30, 35, 40, 28, 33, 29, 45, 31, 27],
    'City': ['Delhi', 'Chandighar', 'Mumbai', 'Ahmad Nagar', 'Pune',
             'Patna', 'jaipur', 'hydrabad', 'Nasik', 'Surat'],
    'Salary': [50000, 60000, 70000, None, 55000, 65000, None, 80000, 62000, 58000]
}

In [23]:
df = pd.DataFrame(data)

In [25]:
# 1. Info and describe
print("Information")
df.info()
print("\n describe")
print(df.describe())

Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

 describe
             Age       Salary
count  10.000000      8.00000
mean   32.300000  62500.00000
std     6.201254   9319.71796
min    25.000000  50000.00000
25%    28.250000  57250.00000
50%    30.500000  61000.00000
75%    34.500000  66250.00000
max    45.000000  80000.00000


In [26]:
# 2. Select Name and City columns

print("\ Selected columns (Name, City)")

print(df[['Name', 'City']])

\ Selected columns (Name, City)
     Name         City
0   Krish        Delhi
1     Ram   Chandighar
2    Sita       Mumbai
3   David  Ahmad Nagar
4   Sumit         Pune
5    Aman        Patna
6     dev       jaipur
7   Anish     hydrabad
8  Raghav        Nasik
9  Waquar        Surat


In [28]:
# 3. Drop City column
df_no_city = df.drop('City', axis=1)
print("\n After dropping City column")
print(df_no_city.head())


 After dropping City column
    Name  Age   Salary
0  Krish   25  50000.0
1    Ram   30  60000.0
2   Sita   35  70000.0
3  David   40      NaN
4  Sumit   28  55000.0


In [29]:
# 4. Fill missing Salary with mean

mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\n After filling missing Salary values")
print(df)


 After filling missing Salary values
     Name  Age         City   Salary
0   Krish   25        Delhi  50000.0
1     Ram   30   Chandighar  60000.0
2    Sita   35       Mumbai  70000.0
3   David   40  Ahmad Nagar  62500.0
4   Sumit   28         Pune  55000.0
5    Aman   33        Patna  65000.0
6     dev   29       jaipur  62500.0
7   Anish   45     hydrabad  80000.0
8  Raghav   31        Nasik  62000.0
9  Waquar   27        Surat  58000.0


C:\Users\DELL\AppData\Local\Temp\ipykernel_13056\1942117672.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)


In [30]:
# 5. Remove duplicate rows (if any)
df.drop_duplicates(inplace=True)
print("\n After removing duplicates (no changes here)")
print(df)


 After removing duplicates (no changes here)
     Name  Age         City   Salary
0   Krish   25        Delhi  50000.0
1     Ram   30   Chandighar  60000.0
2    Sita   35       Mumbai  70000.0
3   David   40  Ahmad Nagar  62500.0
4   Sumit   28         Pune  55000.0
5    Aman   33        Patna  65000.0
6     dev   29       jaipur  62500.0
7   Anish   45     hydrabad  80000.0
8  Raghav   31        Nasik  62000.0
9  Waquar   27        Surat  58000.0
